### PR TITLE
Add golang github actions

### PR DESCRIPTION
**Pull request by jooola**
This will add some CI testing linting and building.

A test needs to be fixed. Please either edit my PR or fix it in master I'll rebase upon the fix.

### CODE REVIEW

**Comment by jooola** [comment]
Please see  https://github.com/jooola/zabbixctl/runs/323253297

**Comment by kovetskiy** [comment]
I've fixed the issue, could you please rebase your fork and check that action?

**Comment by jooola** [comment]
Done, this is now a basic CI. I'll submit another PR to setup release process.

Also I might come up with a bigger PR to restructure the project.

**Comment by jooola** [comment]
See https://github.com/jooola/zabbixctl/runs/323476691

**Comment by kovetskiy** [comment]
Thanks!

**Pull request merged**
